### PR TITLE
Wind forcing

### PR DESCRIPTION
**Pull request by setmar**

### CODE REVIEW

**Comment by setmar** [comment]
Kom visst med noen commits for mye her. Forhåpentligvis går det greit å merge likevel. Hvis ikke så skal jeg rydde opp PR-en.

**Comment by setmar** [comment]
[Implementation of wind, given direction + amplitude](https://trello.com/c/gXTdl9k6/6-implementation-of-wind-given-direction-amplitude)

**Comment by havahol** [comment]
What are the new simulator parameters offset_x and offset_y?

**Comment by havahol** [comment]
It should be specified what is meant by wind direction. Wind direction 0.0 corresponds to north, but does that mean that the wind comes from north, or goes towards north? And does direction 90.0 correspond to east or west (are the degrees clockwise or counter-clockwise)?

My intuition (which can be wrong, ofc):
- Direction should corresponds to the velocity field. Tests with f=0 and direction=0.0 shows that water pile up in the south, hence the wind blows from north towards south.
- When a direction represent an angle, the typical convention is that counter-clockwise is positive. Hence, direction=90 from north should be west. With f = 0 and direction = 90, water pile up in the west, and hence the wind goes from east towards west.

These two points don't correspond with each other.

**Comment by havahol** [comment]
kernel functions wind_downwind_direction and wind_dd are not used.

It would also be nice to put a reference for the C_drag parameter somewhere :)

**Comment by setmar** [comment]
All comments have been addressed in the latest commit in the PR.

**Pull request merged**
