### PR TITLE
Updated numerical order experiments

### PR DESCRIPTION
**Pull request by babrodtk**
This creates figures in the paper now.

Note that I had to revert CDKLM and FBL to get proper convergence (see #153  and #152 )

### CODE REVIEW

**Comment by havahol** [comment]
Since this PR is a rollback of a large optimization effort, I recommend that we do not merge, but instead aim to prioritize to get some time to fix the bugs that caused the need for rollback.

**Comment by setmar** [comment]
Can this PR now be closed, or are there more changes here that should be merged which was not a part of PR #158 ?

**Comment by havahol** [comment]
The bug that required a FBL rollback is still not fixed. See issue #152

**Comment by babrodtk** [comment]
This is really outdated. Closing

**Pull request closed without merging**
